# Auto-Generated ETL Script
# Generated by: SpecGen v0.1
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)

# Op: op_001_load
source_raw_data.csv <- read_csv("source_raw_data.csv")

# Op: batch_op_002_compute
ds_002_derived <- source_raw_data.csv %>%
  mutate(
    x = val1 + val2,
    y = x * 2
  )

# Op: op_004_exec
ds_003_materialized <- ds_002_derived

# Op: op_005_save
write_csv(ds_003_materialized, "file_final_output.csv")
