# Auto-Generated ETL Script
# Generated by: Unknown
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)

# Op: op_load
raw_data.csv <- read_csv("raw_data.csv")

# Op: batch_op_calc_x
ds_step2 <- raw_data.csv %>%
  mutate(
    x = val1 + val2,
    y = x * 2
  )

# Op: op_save
write_csv(ds_step2, "final_output.csv")
