import pytest
from src.ir.model import Pipeline
from src.generator.builder import RGenerator

class TestRStructure:
    
    def test_generates_standard_imports(self):
        """
        Scenario: Every R script must import the Tidyverse and Lubridate.
        """
        # Empty pipeline
        pipeline = Pipeline(datasets=[], operations=[])
        
        generator = RGenerator(pipeline)
        code = generator.generate()
        
        # Verify imports exist
        assert "library(tidyverse)" in code
        assert "library(lubridate)" in code
        
    def test_generates_header_comments(self):
        """
        Scenario: The script should verify it was auto-generated.
        """
        pipeline = Pipeline(
            metadata={"generator": "ETL Optimizer v1.0"}, 
            datasets=[], 
            operations=[]
        )
        
        generator = RGenerator(pipeline)
        code = generator.generate()
        
        assert "# Generated by: ETL Optimizer v1.0" in code
        assert "# Dialect: Tidyverse" in code